### PR TITLE
Tune camb fit

### PR DESCRIPTION
**Pull request by andreufont**
Trying to speed up CAMB calls when doing fits, related to issue #66 .

full_theory.get_emulator_calls last still 1.2 seconds, so probably room for a bit more tuning?

At any rate, we should merge these changes for now.

### CODE REVIEW

**Comment by Chris-Pedersen** [comment]
Ran some quick tests running 50 likelihood evaluations:

on master before this PR:
times_old_kmax-1

on this PR as of the most recent commit:
times_new_kmax-1

on this PR dropping the lensing etc calcluations that Pablo suggested:
times_newer-1

sorry the figures are kind of massive. I'm a bit suprised that changing k max had such a small effect, but this is quite a good improvement when we include Pablo's changes. I'll add a commit in a sec.

**Comment by Chris-Pedersen** [comment]
I've added the `CAMB` settings that drop extra calculations. There are circumstances where we might want these though (such as derived parameters) for notebooks, so we should have some option whether or not to include them. I need to press on with the draft for now, but I can add this later today or tomorrow if you don't have time.

**Comment by andreufont** [comment]
It was complicated to have at the same times objects asking for fast_camb (limited k-range, speed-up calculations), while at the same time being able to make nice plots in notebooks. I had to do a lot more changes than I wanted, but I think I'm happy with the results now. 

I tested notebooks, but only the mini-sampler-test notebook. You might want to cross-check one of the standard samplers. Note that now we do expect order 1e-4 changes, since we are asking for slightly different CAMB calls.

**Comment by Chris-Pedersen** [comment]
Sampler results look good, thanks for updating the sampler scripts too. This all works fine for me so going to merge.

tune_camb_test

**Pull request merged**
