### PR TITLE
Hide set t0

### PR DESCRIPTION
**Pull request by andreufont**
Hide set_T0 and set_gamma from fake_spectra unless you are trying to vary them. This allows one to use fake_spectra from the main fork when not dealing with temperature rescalings. 

This addresses issue #105 , that uses now the main function to extract skewers with rescalings, just set to no rescaling.

### CODE REVIEW

**Review by andreufont — COMMENTED** [review]
@Chris-Pedersen , I tested the code without rescaling, and it works well. By looking at the very minor changes I'm sure it will be fine for others, so I think we can merge straight away.

**Review by Chris-Pedersen — COMMENTED** [review]
Just wondering what's the motivation for the changes to full_theory?

**Comment by Chris-Pedersen** [comment]
Other than that it all looks good, happy to merge

**Comment by andreufont** [comment]
Setup.py at PIC sent several warnings about the if statement, and suggested the changes. It shouldn't matter.

**Pull request merged**
