### PR TITLE
Refactor package

### PR DESCRIPTION
**Pull request by Chris-Pedersen**
When planning out the changes for the postprocessing restructure, it seemed like a good opportunity to do what we've been wanting to do for a while, and refactor the code into a single python package with submodules. This will avoid us having several different `setup.py` and independent modules floating around.

This is most of the way there but with a bit of tidying up to do which I'll finish over the next few days. I will remove the old .py files and tidy up the rest of the repo before merging.

### CODE REVIEW

**Comment by andreufont** [comment]
Sounds good, thanks for looking into this.

**Comment by Chris-Pedersen** [comment]
Hi @andreufont all parts of the code necessary to run a chain (i.e. cosmology, arxiv, emulator, likelihood & sampler objects) are now working both on my desktop and Hypatia. I have stored all the old notebooks in `notebooks/old` for now. Over the next few weeks I'll update them as I go to the new format, and eventually we can delete this directory. I think this is probably a good time to merge though. Do you want to take a look at the new structure in https://github.com/andreufont/LyaCosmoParams/tree/refactor_package and see if you want any changes before merging?

I will branch this and start work on the postprocessing restucture in the meantime.

**Comment by andreufont** [comment]
Hi @Chris-Pedersen - I should be able to review it and test it on my laptop, but not today. Maybe Monday?

**Comment by Chris-Pedersen** [comment]
@andreufont Ok sounds good

**Pull request merged**
