### PR TITLE
Fix data

### PR DESCRIPTION
**Pull request by andreufont**
Fixed code to read covariance matrices

### CODE REVIEW

**Review by andreufont — COMMENTED** [review]
I also had to modify other pieces, since I decieded to remove two options that were not used any more: toy_data and blind_data.

**Comment by andreufont** [comment]
Yes, @keirkwame , this is the other thing I suggested to check. One could run the sampler without the contribution from the emulator covariance, or test the other limit by reducing the data covariance by an arbitrary factor (say, 10).

**Comment by keirkwame** [comment]
Yep - or even as a first thing, what are the relative contributions to each element of the covariance?


Otherwise, am I to understand that the Chabanier+ covariance, because of an increased systematics budget, is of the same magnitude as the P-D+? Is this true on the off-diagonals as well?


Keir


________________________________

**Comment by andreufont** [comment]
That's the crazy thing. They add statistics and systematics at the variance (in quadrature), and use a correlation matrix to build a covariance matrix from there. They construct the correlation matrix from bootstrapping, I think. 

I agree though that it would be good to see plots of the covariance matrix for different redshifts, with and without the (typical) emulator error. Not sure how to choose what "typical" is. The correlation matrix for the emulator covariance is just the outer produce of the median that is subtracted, right?

**Comment by keirkwame** [comment]
Right! But they get "improved" parameter constraints in their analysis, no?


K


________________________________

**Comment by andreufont** [comment]
Yes, they do. They also use a different analysis setup, they don't re-run the analysis on the old dataset with the new "pipeline".


________________________________

**Comment by Chris-Pedersen** [comment]
Some plots below of the covariance and correlation matrices - for the emulator calls I've just chosen our fiducial Planck cosmology which lies near the centre of the LH. We can look at more extreme parts of parameter space, but for now this is roughly typical of the parts of parameter space we make the majority of the emulator calls.

covmats

It looks like biggest differences between PD2013 and Chabanier2019 is in the regions of high uncertainty, so it makes sense we do not see a huge change in the constraining power. The correlation matrices (NB the colorbar limits are truncated) show a slightly larger contribution from the off-diagonals in Chabanier2019, but this is very minor

cormats

Running a chain halving the data covariance sees a significant increase in the precision of constraints, so I'm convinced we're not dominated by emulator error.

halfdatacov

I also ran a chain with 10% data covariance, but for some reason this is failing to converge within normal timescales, will see how that progresses. Finally, turning off the emulator covariance gives slightly biased results, although hard to say to what extent this is specific to just this test simulation, would probably be worth repeating this on a few others.

noemucov

But it does seem that the emulator covariance, while not dominating the constraints, is still proving valuable in returning unbiased results.

**Comment by andreufont** [comment]
Thanks for the plots, @Chris-Pedersen, I think we can merge.

 To sum up:
 - from statistics only, cov_2019 is indeed much more constraining that cov_2013. 
 - systematic errors are larger in cov_2019 than in cov_2013.
 - taking into account both, cov_2019 is only marginally better than cov_2013.
 - for both cases, for Planck cosmo, cov_emu is non-negligible, specially at low-k. 
 - for points further away from the center of the LH, cov_emu will likely be somewhat larger.

**Comment by Chris-Pedersen** [comment]
Agreed, merging!

**Pull request merged**
