### PR TITLE
August update

### PR DESCRIPTION
**Pull request by Chris-Pedersen**
This PR will include a few updates to the code:
1. Gaussian priors on the sampler
2. An option to train the Gaussian process emulator using an asymmetric kernel
3. An option to run the sampler on mock data created in MP-Gadget rather than the PD2013 data.

### CODE REVIEW

**Comment by Chris-Pedersen** [comment]
[mock_data_test.pdf](https://github.com/andreufont/LyaCosmoParams/files/3530039/mock_data_test.pdf)

Mock data created in MP-Gadget using PD2013 covariance, overlaid on the PD2013 P1D.

**Comment by andreufont** [comment]
Awesome! 

Another related thing that would be happy is to have a set of likelihood parameters that describe the simulation, that we can use as our default if we just want something that fits the data.

**Comment by Chris-Pedersen** [comment]
Yes agreed, I have a script to do this, it takes a while to generate TDR for the 1024s but I'll set it running now and add the plots/data here when its done.

**Comment by andreufont** [comment]
Great. 

How should we proceed with the merging of the PR? I'd like to use the mean flux emulator in combination with this mock data, so probably easier if we merge one of them (or two) into master, right?

**Comment by Chris-Pedersen** [comment]
Yes I think we should get everything merged onto master asap. I will need to make some changes to the likelihood class to work with the mock data. Probably the best approach is to merge #38 to master first, then I'll finish this and merge it this afternoon.

**Comment by andreufont** [comment]
could you take care of merging master into this branch?

**Comment by Chris-Pedersen** [comment]
Yes of course! Just making sure everything works smoothly.

**Pull request merged**
