### PR TITLE
Parallelise sampler

### PR DESCRIPTION
**Pull request by Chris-Pedersen**

### CODE REVIEW

**Comment by Chris-Pedersen** [comment]
This has become a monster PR so documenting some of the changes so far:

1. Parallelised the sampler to run across multiple cores on one node using `emcee` and `multiprocessing.pool`
2. Added a range of emulator options, including an option to emulate (1+k)*P1D(k), P1D(k)/(1+z)^3.8, and emulate P1D of F instead of delta_F
3. Added the Australia20 suite to the repo
4. Re-parametrised the likelihood parameters to use a multiplicative rescaling of a fiducial IGM model.
5. Added an acquisition function to the likelihood class
6. Samplers will now run using a standardised set of emulator hyperparameters instead of retraining on each training set.

**Comment by Chris-Pedersen** [comment]
To do in the next PR:

1. Fix `recons_cosmo` to work with g_\star sampling
2. Add Chabanier2019 covmats
3. Improve acquisition function code
4. Extend arxiv code to manage the new h and nu_sims
5. Modify `setup_simulation` code to work in km/s units with a km/s pivot rather than Mpc

**Comment by andreufont** [comment]
This is great, thanks @Chris-Pedersen!

About those five points, I'd really try to make these 5 different issues, addressed in 5 different branches, and approved in 5 different PR.

**Comment by Chris-Pedersen** [comment]
Yes agreed!

**Pull request merged**
